# Generated by Django 2.0.5 on 2018-05-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='color',
            field=models.CharField(default='l', max_length=3),
        ),
    ]
