# Generated by Django 2.0.5 on 2018-05-04 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='color',
        ),
    ]
